_wandb:
    value:
        cli_version: 0.25.1
        e:
            rbx91ejr7z8rrfgu4gputyayxpr1ddy4:
                apple: {}
                args:
                    - wandb_mode=online
                codePath: pokeagent/local_llm_qlearn.py
                codePathLocal: pokeagent/local_llm_qlearn.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "208432869376"
                email: yuqifu@cs.toronto.edu
                executable: /Users/ginny/Documents/course-25FALL/introduction_to_machine_learning/final/reward-shaping-rl/.venv/bin/python
                git:
                    commit: 964ea1bc13a0ae5f0768eb726877ad7210a43f78
                    remote: https://github.com/alexzhang13/reward-shaping-rl.git
                host: Mac
                memory:
                    total: "25769803776"
                os: macOS-26.3.1-arm64-arm-64bit-Mach-O
                program: /Users/ginny/Documents/course-25FALL/introduction_to_machine_learning/final/reward-shaping-rl/pokeagent/local_llm_qlearn.py
                python: CPython 3.13.7
                root: /Users/ginny/Documents/course-25FALL/introduction_to_machine_learning/final/reward-shaping-rl
                startedAt: "2026-03-28T22:09:03.463784Z"
                writerId: rbx91ejr7z8rrfgu4gputyayxpr1ddy4
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 50
                - 95
                - 105
            "2":
                - 1
                - 50
                - 95
                - 105
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
cost_budget:
    value: 1
eval_max_steps:
    value: 50
evaluate:
    value: false
feedback_frequency:
    value: 50
game_name:
    value: MountainCar-v0
llm_type:
    value: gpt-3.5-turbo
lr:
    value: 0.1
max_episodes:
    value: 1000
max_prompt_size:
    value: 3800
max_tokens:
    value: 500
seed:
    value: 0
train_iterations:
    value: 500
wandb_gen_id:
    value: mountain_car_llm_v1
wandb_mode:
    value: online
wandb_name:
    value: debug
wandb_project:
    value: reward-shaping
